server:
  port: 2333
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5EMBEDDED
      - TV
      - WEB
      - MUSIC
      - ANDROID_VR
      - M_WEB
      - ANDROID
      - ANDROID_MUSIC
      - WEBEMBEDDED
      - TVHTML5
    oauth:
      enabled: false
      refreshToken: "${GOOGLE_REFRESH_TOKEN}"
      skipInitialization: true
    pot:
      token: "CgtLYnJKeDl1N0pJMCjW2cO8BjIKCgJERRIEEgAgKg=="
      visitorData: "MnRuJyEtJOv8LW4fImJbwY4qXcflEPdSWXwKWnQappnJt4Ee_3bFCJEUmiePXV3jvyjxMuT8pE3j-ZKoLtF-bIjo7-erKATkj38QRYgrGRsEHDC97Qk9a-tcYdXpmMQt2h6A1S325QgSsRfbfjBfBTeDq_oZBA=="

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false # Disable default youtube source in favor of the plugin
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: false
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true


