server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      snapshot: false
  server:
    password: "remani-lavalink"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID_VR
    pot:
      token: "MtIECHfFk13fuLMISXdw-cBhZzl_WRzuixurG1hLDVR4qI7hRnVSVAzfityu8nCqNQD5GvEsCaDLSoG0N-ANHPbloZ4V1jwmScCfsZkJ2fj_4-Dxutuk2b9CygcG7qTUeOydpuxnh3Kw6Grnjvqd11u7my_9GLibIEc7MvX7oyqsi-Dry20AqwFy6RAs1mUZR6ATGgpe1PKDkgbyjewZFP6L-Ba8E5LX7gk5I3vsFQ2CWQoNTzPdmWZFk4KzAtrjnhzeZ4fomI6KDMXgizlmMPRkPw4mPSJqeiAOt-9EVqCfN0a5_MSk09vhhyhn1dGvoWqDk2KA2XTReuB5KyGuojHJwmGtAeQTeQinEbI8q-oAJSXUrsNQ4YJIxSJZ3-b4eG9bw5lndledjN-P8HRvBURYKnSDBzgc6JY7UBrR0DF82_0wND1hVp9KYJDuzbtIMy48qRNjCU5gyJfKHCi6BDYPjPgMqkV82Olj54u37i2Q76ULDxZ07t6iz7vOX7RJL5D8Vwr9M976qTVfQFgGh9FXyGu_dCWvpvxwHGYv5VzR6sM68wr1koNapZ2Ncze7Pnr7mFxWjoKY_k1UEwaO26BoEn8f9E4zY82mUTEh7TlnB5m8K-BcqKPYiDtPJAvUDKPsFf4ETMkkPFMGPe4MB668OWsGslm1pJLhKLQY67rz7giKgcSMcRlYRpHoNp5g-QEuTEBvjp_Yhg-2p7y6zXmW8tyE-MZm04Tv6YvYrBUVPZ0xYzPiS66UucVdVptlrwkX7srGgqSKZ3sVUMwtg0dNL6_0"
      visitorData: "Cgs4MVVVQnY4OFBrRSiAp4jNBjIKCgJJThIEGgAgTGLfAgrcAjE2LllUPWZnak00WHVaZVRYdjNLdWJTYlpMeWROZVc5N01pblhuM25HdWxjMlJ6OFlqelBkOVlCc3lHODYwdXgxM3NhODdPRkhGakJYSUJtZGlJcnBHN0pXYk5Nd3Y2bGpabF9SSWg0N0ZHekVBdVBFcTg3OTJVbHlGQTU4dm00cE1MZXJkNV9UamVtVHU3eC1sc0FkaGE5a0NkQXhuX2RjWXl4MDczZ2ZmUVBXaGdtUE5PSVZKX1JqYkpaSm1SLUxLY3VmZ2k4b1E0N0pFb3dqRzIwXzZNZGZ2S2dRN2dFWHF4M1VqbWlZTGNGSFJWVlVFTVNhVmhvTW9Yd1o3dGhTUGl2TmtRSG9veThQQU83N0E4a2UzSkhmSXh4VW9pWUs4Uk5ZbHN1NE9WT2Q4c1FGOWNzcVU2UEhzUkRKZ0RsSUFkdUNBMjZYeklfRHBra2lZWFpFejMtSTVZQQ%3D%3D"
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
      userAgent: "remani-bot"
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN:}"

  lavasrc:
    providers:
      - 'ytmsearch:"%ISRC%"'
      - "ytmsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6

logging:
  level:
    root: INFO
    lavalink: INFO

  file:
    max-history: 7
    max-size: 10MB
